server:
  applicationConnectors:
    - type: http
      port: ${PORT}
  adminConnectors:
    - type: http
      port: 5001

# Database settings.
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: ${dw.database.user}
  # the password
  password: ${dw.database.password}
  # the JDBC URL;
  url: ${dw.database.url}

salt: ${dw.salt}
secretKey: ${dw.secretKey}
authToken: ${dw.authToken}

siteDomain: ${dw.siteDomain}
siteName: ${dw.siteName}

#email
emailUser: ${dw.emailUser}
emailHost: ${dw.emailHost}
emailPassword: ${dw.emailPassword}

tinypngKey: ${dw.tinypngKey}
awsConfig:
  s3AccessKey: ${dw.awsConfig.s3AccessKey}
  s3SecretKey: ${dw.awsConfig.s3SecretKey}
  bucket: ${dw.awsConfig.bucket}
  bucketUrl: ${dw.awsConfig.bucketUrl}
  s3Region: ${dw.awsConfig.s3Region}




