name: Deploy ElsieGram-API

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Heroku CLI
      run: brew tap heroku/brew && brew install heroku
    - name: Login to Heroku, Set remote branch, push master branch
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY_ELSIEGRAM_API }}
      run: heroku container:login && heroku git:remote -a elsiegram-api && git push heroku HEAD:master